- name: Setup cloudtoken # based on https://developer.atlassian.com/cloud/tool/cloudtoken/install/macos/
  hosts: all
  gather_facts: True
  tags: cloudtoken
  tasks:
    - name: Add cloudtoken homebrew tap
      homebrew_tap:
        url: git@bitbucket.org:atlassian/cloudtoken-homebrew-tap.git
        name: atlassian/cloudtoken
    - name: Install cloudtoken
      homebrew_cask:
        name: cloudtoken
    - name: Make sure config dir is present
      file:
        path: ~/.config/cloudtoken
        state: directory
    - name: Copy config file
      template:
        src: config.yaml.j2
        dest: ~/.config/cloudtoken/config.yaml
        mode: 0600
